// 位置
export const CHANGE_CURRENT_CITY = 'CHANGE_CURRENT_CITY'
export const CHANGE_LOCATION_INFO = 'CHANGE_LOCATION_INFO'
export const CHANGE_LOACTION_DETAIL_INFO = 'CHANGE_LOACTION_DETAIL_INFO'

// 客服
export const CHANGE_CUSTOMER_SERVICE_INFO = 'CHANGE_CUSTOMER_SERVICE_INFO'
export const CHANGE_WSINFO_INFO = 'CHANGE_WSINFO_INFO'
export const CHANGE_WS_INFO = 'CHANGE_WS_INFO'
export const CHANGE_CHAT_LIST = 'CHANGE_CHAT_LIST'
export const CHANGE_ON_FN = 'CHANGE_ON_FN'

// app
export const CHANGE_IS_IN_MINIPROGRAM = 'CHANGE_IS_IN_MINIPROGRAM'
export const CHANGE_SYSTERM_INFO = 'CHANGE_SYSTERM_INFO'
export const CHANGE_USER_PAGE_SCROLL = 'CHANGE_USER_PAGE_SCROLL'
