// 位置
export const CHANGE_CURRENT_CITY = 'CHANGE_CURRENT_CITY'
export const CHANGE_LOCATION_INFO = 'CHANGE_LOCATION_INFO'
export const CHANGE_LOACTION_DETAIL_INFO = 'CHANGE_LOACTION_DETAIL_INFO'

// 客服
export const CHANGE_CUSTOMER_SERVICE_INFO = 'CHANGE_CUSTOMER_SERVICE_INFO'
export const CHANGE_WSINFO_INFO = 'CHANGE_WSINFO_INFO'
export const CHANGE_WS_INFO = 'CHANGE_WS_INFO'
export const CHANGE_CHAT_LIST = 'CHANGE_CHAT_LIST'
