export const CHANGE_J_CURRENT_LOCATION = "CHANGE_J_CURRENT_LOCATION";
export const CHANGE_DEFAULT_LOCATION = "CHANGE_DEFAULT_LOCATION";
export const CHANGE_CURRENT_LONGITUDE_AND_LATITUDE = "CHANGE_CURRENT_LONGITUDE_AND_LATITUDE";
