export const navs = {
  styles: {
    width: "80upx",
    height: "80upx",
    radius: "20upx",
    iconWidth: "60upx",
    rowBottom: "36upx",
  },
  titleStyles: {
    color: "#3d3d3d",
    "margin-top": "20upx",
    fontSize: "24upx",
  },
  rows: 4,
  navs: [
    {
      label: "草帽服饰",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/pv1rn9fgnioonh5zhfat.png",
      background: "linear-gradient(152deg, #07B9B9, #07B9B9)",
      width: "56upx",
      url: "/marketing-treasure-house/article-list?type=1&title=草帽服饰",
    },
    {
      label: "酒店营销",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/ace6i9kivpfonlmogr3l.png",
      background: "linear-gradient(146deg, #3662EC, #8A38F5 )",
      width: "45upx",
      url: "/marketing-treasure-house/article-list?type=2&title=酒店营销",
    },
    {
      label: "美容美发",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/7iaabyvc8vvq3xpvlr9u.png",
      background: "linear-gradient(142deg, #EB2F96, #FA5151)",
      url: "/marketing-treasure-house/article-list?type=3&title=美容美发",
      width: "45upx",
    },
    {
      label: "生活超市",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/xkgxzap1rgbqa3mc24p1.png",
      background: "linear-gradient(136deg, #FF8F1F, #FA5151)",
      width: "54upx",
      url: "/marketing-treasure-house/article-list?type=4&title=生活超市",
    },
    {
      label: "健身娱乐",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/teoll5bst6hd8xv1azfn.png",
      background: "linear-gradient(148deg, #FF8F1F, #FA5151)",
      width: "50upx",
      url: "/marketing-treasure-house/article-list?type=5&title=健身娱乐",
    },
    {
      label: "装修建材",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/0h0loeosremt8rg3z3c3.png",
      background: "linear-gradient(142deg, #00B578, #07B9B9)",
      width: "40upx",
      url: "/marketing-treasure-house/article-list?type=6&title=装修建材",
    },
    {
      label: "培训学校",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/n4rkcumxu8mk3jwf3zxp.png",
      background: "linear-gradient(145deg, #07B9B9, #00B578)",
      width: "56upx",
      url: "/marketing-treasure-house/article-list?type=7&title=培训学校",
    },
    {
      label: "汽车美容",
      icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/8m1s477a8m1m70xaxiw5.png",
      background: "linear-gradient(145deg,#3662EC , #8A38F5)",
      width: "48upx",
      url: "/marketing-treasure-house/article-list?type=8&title=汽车美容",
    },
    // {
    //   label: "爆粉秘籍",
    //   icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/5qvq36u9kv893o2g0z0d.png",
    //   background: "linear-gradient(148deg, #FA5151, #FF8F1F)",
    //   width: "44upx",
    //   url: "/marketing-treasure-house/article-list?type=9&title=爆粉秘籍",
    // },
    // {
    //   label: "抖音实例",
    //   icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/6cex483e3vok0m3z5tw2.png",
    //   background: "linear-gradient(138deg, #EB2F96, #FA5151)",
    //   width: "36upx",
    //   url: "/marketing-treasure-house/article-list?type=10&title抖音实例",
    // },
    // {
    //   label: "营销课程",
    //   icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/ioxwrg755riv30ippijz.png",
    //   background: "linear-gradient(143deg, #8A38F5, #EB2F96)",
    //   width: "54upx",
    //   url: "/marketing-treasure-house/article-list?type=11&title=营销课程",
    // },
    // {
    //   label: "赚钱教程",
    //   icon: "https://www.tuanfengkeji.cn:9527/jf-admin-api/admin/storage/fetch/xs58stz7qxkphdxxwfjh.png",
    //   background:
    //     "linear-gradient(140deg, #FF8F1F, #FA5151)",
    //   width: "50upx",
    //   url: "/marketing-treasure-house/article-list?type=12&title=赚钱教程",
    // },
  ],
};
