// auth
export const J_USER_INFO = "J_USER_INFO";
export const J_USER_TOKEN = "J_USER_TOKEN";
export const J_TOKEN_EXPIRE = "J_TOKEN_EXPIRE";

// search
export const J_ARTICLE_SEARCH_HISTORY = "J_ARTICLE_SEARCH_HISTORY";
export const J_GOODS_SEARCH_HISTORY = "J_GOODS_SEARCH_HISTORY";
export const J_STORE_SEARCH_HISTORY = "J_STORE_SEARCH_HISTORY";
